### ISSUE TITLE
Return value of \"OC\\Core\\Command\\User\\ListCommand::execute()\" must be of the type int, NULL returned

### ISSUE THREAD

**Issue by ifuchs** [Adphi/occweb#1]
(Probably very) simple question: When I issue most commands (e.g., user:list), I get:
occ $ user:list
[object Object]

What am i missing?

**Comment by Adphi** [comment]
The `[object Object]` is due to the lack of proper error handling ... sorry about that. Do you have any error message in the nextcloud logs or in the browser console ?

**Comment by ifuchs** [comment]
There is nothing in the browser console. The log entry is a bit long but here is the beginning and end (if that helps):

{"reqId":"qK4b7bX2HYKJyq8ifGSu","level":3,"time":"2020-04-17T13:57:26+00:00","remoteAddr":"192.168.3.1","user":"admin","app":"index","method":"POST","url":"/apps/occweb/cmd","message":{"Exception":"Exception","Message":"Return value of \"OC\\Core\\Command\\User\\ListCommand::execute()\" must be of the type int, NULL returned.","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->",”args"

and ends with 

,"File":"/var/www/html/custom_apps/news/vendor/symfony/console/Command/Command.php","Line":258},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0","version":"18.0.2.2”}

If you need all of it, let me know.

Also, the command occ user:list (as one example) runs fine in the terminal console on the container.

**Comment by Adphi** [comment]
> If you need all of it, let me know.

Yes, please. The full stacktrace would help.

**Comment by ifuchs** [comment]
[occweb-log.log](https://github.com/Adphi/occweb/files/4493722/occweb-log.log)

**Comment by Adphi** [comment]
Ok. I just saw that I missed a similar issue on the original gogs repository. You both have the news app showing in the stack trace...

I just did a test :  
- start a Nextcloud (apache based) docker container
- installed occweb
- run `occ user:list`: works
- install the **news** app
- run `occ user:list` again: `[object Object]`

**Comment by Adphi** [comment]
The news app is vendoring a version of the `Symfony console` :
> "/var/www/html/custom_apps/news/vendor/symfony/console/Command/Command.php"

It seems to conflict with the one embedded in Nextcloud in the `OccController` imports : 
https://github.com/Adphi/occweb/blob/4fecde9d9d750088f0d2bc31229cda6e34af39aa/lib/Controller/OccController.php#L14

**Comment by ifuchs** [comment]
Not sure what that means. Is there another console app available as a
result of installing news? Are OCCweb and news basically incompatible?

**Comment by Adphi** [comment]
You could just delete the `console` folder from **news** vendoring: 
```bash
rm -rf /var/www/html/custom_apps/news/vendor/symfony/console/
```
I did it and the **news**' `occ` commands are still working (as the Nextcloud one must be used). 
If you experience problems, you will only need to uninstall, remove and reinstall the **news** app.

They already have a (closed) [issue](https://github.com/nextcloud/news/issues/621) mentioning the problem.

Closing as the problem comes from **news**.

**Comment by ifuchs** [comment]
Thanks. Deleting Console fixed occweb. Just curious, can you tell me the purpose of console in the News app?

**Comment by Adphi** [comment]
Each nextcloud app can expose maintenance commands that will be registered to the main occ command. Nextcloud uses the Symfony command module for this. Just enter help and you will see the **news** commands, `occ news:*`

**Comment by peteman52** [comment]
OK, deleting News:Console fixed problem for me too. Thank you very much!
