### ISSUE TITLE
Is app still depreciated?

### ISSUE THREAD

**Issue by Albirew** [Adphi/occweb#3]
I discovered you moved from your gogs forge to github and released a new version (witch is greatly appreciated! seriously!)
Does this means app is less depreciated? And in witch way: active dev or community-maintained?

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by Adphi** [comment]
@p-bo yes, it is more than ever. I'm sorry.
I have some ideas on how to make this work, but it's far too hacky for me to accept to implement it. Again... sorry.
