### ISSUE TITLE
NC26 - Exception: Cannot access private property OC\Console\Application::$application

### ISSUE THREAD

**Issue by Ralf99** [Adphi/occweb#5]
Hello all,

I have the following error in my logging after updating to version 26.0.0.11:

Exception: Cannot access private property OC\Console\Application::$application in file '/nextcloud/apps/occweb/lib/Controller/OccController.php' line 81

and the app does not work anymore. 

Lines 80-87 are as follows:
  public function list() {
    $defs = $this->application->application->all();
    $cmds = array();
    foreach ($defs as $d) {
      array_push($cmds, $d->getName());
    }
    return new DataResponse($cmds);
  }

Line 81:
$defs = $this->application->application->all();

I know OCC Web is no longer supported but up to version 24 the app still worked to execute occ commands.
**My question now, how would line 81 have to be changed to make occ web work again, at least rudimentarily?**

### Steps to reproduce

1. update to version 26
2. open occ web
3. Black surface
4. look into the logging

### Expected behavior

the app opens normally again without a black screen

**Comment by Sedeniono** [comment]
occweb is the only way to execute occ commands if you don't have ssh access, which is not that unusual on certain web hosters. So occweb was the only way to execute the commands recommended after an upgrade of nextcloud in this case.

As a temporary workaround (tested with occweb 0.1.0 on nextcloud 26.0.2): Open the file `lib/private/Console/Application.php` and comment-out the line `private SymfonyApplication $application;` (i.e. put `//` at the beginning of the line). This allows occweb to work again. After executing the desired occ commands in occweb, I would revert the change again, however, and disable occweb.
