### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by bastlerdu** [Adphi/occweb#9]
Hi, if I activate occ_web, I get follwing error: 

Interner Serverfehler
Der Server konnte die Anfrage nicht fertig stellen.
Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.
Technische Details
    Entfernte Adresse: 2001:9e8:c908:100:f110:795c:b375:72f0
    Anfragekennung: ZUFK60tC1dtJNwnk_g3lugAAAAk

I use nextcloud 25.0.13

Regards

**Comment by mteguhfh** [comment]
Internal Server Error 500 :( too
![Screenshot 2023-11-01 134540](https://github.com/Adphi/occweb/assets/17719184/4f98544e-9272-4238-ab6a-5d72b992b79c)

**Comment by nowrap** [comment]
The nextCloud log says:
`OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\OCCWeb\Controller\OccController! Property OC\Console\Application::$application does not exist`

**Comment by Jonas-Schwarz** [comment]
Same here, with nextcloud 28.0.1

[index] Fehler: Call to undefined method OC\Server::getEventDispatcher()

**Comment by genderneutralnoun** [comment]
I'm having this issue, too.

**Comment by moboter** [comment]
Some more detailed Information
Ubuntu 22.04.4 LTS
PHP 8.1.2
Zend OPcache v8.1.2
Apache/2.4.52
Nextcloud 25.0.13

GET","url":"/index.php/apps/occweb/","message":"Could not resolve OCA\\OCCWeb\\Controller\\OccController! Property OC\\Console\\Application::$application does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"25.0.13.2","exception":{"Exception":"OC\\AppFramework\\Utility\\QueryNotFoundException","Message":"Could not resolve OCA\\OCCWeb\\Controller\\OccController! Property OC\\Console\\Application::$application does not exist","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":134,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":466,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":438,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":159,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1053,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","Line":123,"CustomMessage":"--"}}

**Comment by smakdab240** [comment]
> Same here, with nextcloud 28.0.1
> 
> [index] Fehler: Call to undefined method OC\Server::getEventDispatcher()

I found this thread has addressed the issue for me in my NC28 environment.  Hopefully it works for you too.

#10 [https://github.com/Adphi/occweb/issues/10#issuecomment-1979706075](url)
